name: Desktop E-commerce Management Applicaiton

on:
  push:
    branches: ["main", "master"]
    paths: ["frontend/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: cd frontend && npm run test

  
